Ajout d'un lexique au thème 2
gch-poly/gch-python pull request #1
Opened 2022-05-18 00:31 UTC by samayala22

2022-05-18 15:06 UTC, bibeauv requested changes
Vraiment bien le lexique, je trouve que ça fait vraiment un bon résumé ! :)

2022-05-18 15:06 UTC, bibeauv commented on theme2/theme2.ipynb
> +    "- `np.linspace(<debut>, <fin>, <nb de points>)`: génère le nombre de points voulus espacés linéairement\n",
```suggestion
    "- `np.linspace(<debut>, <fin>, <nb de points>)`: génère le nombre de points voulus espacés linéairement. Ici, la valeur de fin est inclue.\n",
```

2022-05-18 15:06 UTC, bibeauv commented on theme2/theme2.ipynb
> +    "- `np.zeros(<dimensions>, dtype=)`: création d'un `ndarray` de zeros, utile pour l'initialisation de vecteurs, matrices que l'on va remplir plus tard.\n",
```suggestion
    "- `np.zeros(<dimensions>, dtype=)`: création d'un `ndarray` de zeros, utile pour l'initialisation de vecteurs ou de matrices qui seront remplis subséquemment dans un code.\n",
```

2022-05-18 15:06 UTC, bibeauv commented on theme2/theme2.ipynb
> +    "- `ndarray.size`: retourne le nombre total d'éléments dans un array\n",
```suggestion
    "- `ndarray.size`: retourne le nombre total d'éléments dans un `ndarray`.\n",
```

2022-05-18 15:06 UTC, bibeauv commented on theme2/theme2.ipynb
> +    "- `ndarray.reshape(<dimensions>)`: changer la forme du array.\n",
```suggestion
    "- `ndarray.reshape(<dimensions>)`: changer la forme d'un `ndarray` selon les nouvelles dimensions spécifiées.\n",
```

2022-05-18 15:06 UTC, bibeauv commented on theme2/theme2.ipynb
> +    "- `ndarray.flatten()`: ramène le array à un vecteur 1D.\n",
```suggestion
    "- `ndarray.flatten()`: ramène le `ndarray` à un vecteur 1D.\n",
```

2022-05-18 15:06 UTC, bibeauv commented on theme2/theme2.ipynb
> +    "- `np.eye(<nb lignes>, <nb colonnes>, dtype=)`: création d'une matrice avec des 1 sur la diagonale. Utiliser `np.eye(<n>)` pour une matrice carrée nxn. \n"
```suggestion
    "- `np.eye(<nb lignes>, <nb colonnes>, dtype=)`: création d'une matrice identité, c'est-à-dire avec des 1 sur la diagonale. Utiliser `np.eye(<n>)` pour une matrice carrée n x n. \n"
```

2022-05-18 15:06 UTC, bibeauv commented on theme2/theme2.ipynb
> +    "### ✔️ Vu dans l'exemple 3\n",
Pour tout ce qui est <dimensions>, il faut faire attention à utiliser un tuple (2,3) pour une matrice. Si on veut créer une matrice de dimension (2,3), il faut faire : `np.zeros((2,3))` et non `np.zeros(2,3)`, sinon ça throw une erreur.
Donc peut-être dire qu'habituellement, les dimensions sont toujours en tuple. Et pour `np.reshape`, je pense que les deux se font. Tu peux utiliser un tuple et tu peux spécifier aussi le nombre de lignes et le nombre de colonnes séparément dans 2 flags différents. Avec `np.eye`, tu expliques justement très bien la distinction !

2022-05-18 15:06 UTC, bibeauv commented on theme2/theme2.ipynb
> +  },
C'est vraiment juste une question d'esthétique, mais desfois tu termines tes _bullet points_ avec un point, desfois non 😄

2022-05-19 02:22 UTC, samayala22 commented on theme2/theme2.ipynb
> +  },
Ouaip je vais régler ça 😅

2022-05-19 03:54 UTC, samayala22 commented on theme2/theme2.ipynb
> +    "### ✔️ Vu dans l'exemple 3\n",
J'ai ajouté un commentaire pour clarifier l'ambiguïté. 👍

2022-05-20 20:26 UTC, bibeauv approved these changes
Excellent !

2022-05-20 20:28 UTC, merged