WIP - Theme4
gch-poly/gch-python pull request #4
Opened 2022-06-29 15:31 UTC by samayala22

- [x] Exemple 1
- [x] Exemple 2
- [x] Exemple 3
- [x] Lexique

2022-07-11 01:09 UTC, blaisb approved these changes
Honnêtement, j'ai juste deux mini commentaires. C'est vraiment du bon boulot...

2022-07-11 01:09 UTC, blaisb commented on theme4/theme4.ipynb
> +    "- [Documentation Polars](https://pola-rs.github.io/polars/py-polars/html/reference/)\n",
Documentation Polars? On parle pas de Pandas ici?

2022-07-11 01:09 UTC, blaisb commented on theme4/theme4.ipynb
> +    "| `sum`, `prod`    | Somme, Produit           |\n"
Dans mon jupyter ce tableau là ne se formattait pas correctement?

2022-07-11 18:00 UTC, samayala22 commented on theme4/theme4.ipynb
> +    "| `sum`, `prod`    | Somme, Produit           |\n"
Sur Colab et Jupyterlite ça marche.

2022-07-11 18:50 UTC, samayala22 commented
https://samayala22.github.io/jpter_lite_test/lab?path=theme4%2Ftheme4.ipynb

Pour tout rouler:

![image](https://user-images.githubusercontent.com/72941105/178337092-b723650f-26d5-4327-b4ba-e02d12fac7c6.png)


Vérifiez que c'est bien la dernière version du notebook. Sinon, il faut supprimer les données locales car le browser garde en cache les données d'executions et des anciennes versions. 

![image](https://user-images.githubusercontent.com/72941105/178336736-c72b1875-22b6-49d9-a3fa-51ca732969c8.png)

![image](https://user-images.githubusercontent.com/72941105/178336801-be352f28-d210-414b-a052-2ac7fe88ce2d.png)

2022-07-13 14:48 UTC, bibeauv requested changes
Méchant beau thème, vraiment de bons exemples, c'est super :)
Mes commentaires sont surtout axés sur les fautes et la syntaxe, donc rien de majeur.
Mon seul commentaire plus spécifique, c'est pour l'exercice d'Ecoinvent, ou je suggère de revenir en g/mol à la fin du code.
Sinon, bravo !!

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "    - Concatener des données\n",
```suggestion
    "    - Concaténer des données\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "    - Groupy et aggregation de données\n",
```suggestion
    "    - Groupy et agrégation de données\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "L'Iris est un genre de plantes vivaces de la famille des Iridacées. Il existe une large variété d'espèces que l'on retrouve au Québec. L'Iris Versicolor est d'ailleur l'un des emblèmes officiels
```suggestion
    "L'Iris est un genre de plantes vivaces de la famille des Iridacées. Il existe une large variété d'espèces que l'on retrouve au Québec. L'Iris Versicolor est d'ailleurs l'un des emblèmes officiels du Québec et se retrouve sur son drapeau.\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "La fleur peut être violette, bleue ou pourpre et plus rarement blanche. Elle est constituée de trois pétales minces et relevés disposés à l'intérieur de la fleur et de trois sépales plus longs e
```suggestion
    "La fleur peut être violette, bleue ou pourpre et plus rarement blanche. Elle est constituée de trois pétales minces et relevées disposées à l'intérieur de la fleur et de trois sépales plus longues et plus larges en forme de spatule et situées à l'extérieur. \n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "filtre = df_iris[\"Espèce\"] == \"Setosa\"  # Masque binaire issu de l'évaluation de la condition \"Espèce == \"Setosa\"\n",
```suggestion
    "filtre = df_iris[\"Espèce\"] == \"Setosa\"  # Masque binaire issu de l'évaluation de la condition \"Espèce" == \"Setosa\"\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "# uniquement les colonnes  Espèce, Petale_long et Petale_larg\n",
```suggestion
    "# uniquement les colonnes "Espèce", "Petale_long" et "Petale_larg"\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "# Attention: ne pas oublier les parentheses entre chaque masque binaire\n",
```suggestion
    "# Attention: ne pas oublier les parenthèses entre chaque masque binaire\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Plutot que d'enchainer plusieurs masques binaires pour évaluer plusieurs égalités, on peut utiliser `.isin` pour isoler les lignes d'une colonne qui contiennent l'une des valeurs possibles d'une
```suggestion
    "Plutôt que d'enchaîner plusieurs masques binaires pour évaluer plusieurs égalités, on peut utiliser `.isin` pour isoler les lignes d'une colonne qui contiennent l'une des valeurs possibles d'une liste."
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "On peut aussi trier les données avec une ou plusieurs colonnes."
```suggestion
    "On peut aussi trier les données avec une ou plusieurs colonnes grâce à `sort_values`."
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "# Trier le tableau par les valeurs de la colonne \"Petale_long\" en ordre decroissant\n",
```suggestion
    "# Trier le tableau par les valeurs de la colonne \"Petale_long\" en ordre décroissant\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "La transestérification est une méthode de production de biodiesel à partir de la réaction entre une huile végétale et de l'alcool. Dans cet exemple, l'huile végétale utilisée est le canola et la
```suggestion
    "La transestérification est un réaction catalytique permettant la production de biodiesel (sous forme d'esters méthyliques) à partir d'huile végétale et de méthanol. Dans cet exemple, l'huile végétale utilisée est le canola et la réaction est la suivante:\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Faire la synthèse des données expérimentales grace à une aggrégation."
```suggestion
    "Faire la synthèse des données expérimentales grâce à une agrégation."
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Les données que l'on analyse sont d'habitude stockées sur un disque dans un fichier. Il existe une multitude de formats qui existent et les plus utilisés sont: `CSV`, `JSON`, `IPC`, `HDF5` et `P
```suggestion
    "Les données que l'on analyse sont habituellement stockées sur un disque dans un fichier. Il existe une multitude de formats qui existent et les plus utilisés sont: `CSV`, `JSON`, `IPC`, `HDF5` et `Parquet`. \n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Dans Pandas, il y a [plusieurs](https://pandas.pydata.org/docs/reference/io.html) fonctions qui permettent de ouvrir ces fichiers et les convertir facilement en `DataFrame`. \n",
```suggestion
    "Dans Pandas, il y a [plusieurs](https://pandas.pydata.org/docs/reference/io.html) fonctions qui permettent d'ouvrir ces fichiers et de les convertir facilement en `DataFrame`. \n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Pour ouvir un fichier la méthode est de la forme `pd.read_<format>(<fichier>)` et pour enregistrer un `DataFrame` dans un fichier, la méthode est de la forme `df.to_<format>(<fichier>)`.\n",
```suggestion
    "Pour ouvrir un fichier, la méthode est de la forme `pd.read_<format>(<fichier>)` et pour enregistrer un `DataFrame` dans un fichier, la méthode est de la forme `df.to_<format>(<fichier>)`.\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Dans la sience des données, l'un des outils fondamentaux est l'aggregation de données qui permet de regrouper les données appartenant à un même sous-groupe et en tirer plus facilement des résult
```suggestion
    "Dans la science des données, l'un des outils fondamentaux est l'agrégation de données qui permet de regrouper les données appartenant à un même sous-groupe et en tirer plus facilement des résultats numériques. \n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Avec pandas, cela se fait avec la méthode `groupby` pour regrouper les données sur une ou plusieurs colonnes et `agg` pour spécifier la méthode d'aggregation employée, très souvent sur les donné
```suggestion
    "Avec pandas, cela se fait avec la méthode `groupby` pour regrouper les données sur une ou plusieurs colonnes et `agg` pour spécifier la méthode d'agrégation employée, très souvent sur les données numériques. Après l'agrégation, une bonne pratique est de renommer les colonnes pour mieux représenter les nouvelles colonnes, avec pandas on peut faire cela avec la méthode `rename`.\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Les opérations d'aggregation possible sont:\n",
```suggestion
    "Les opérations d'agrégation possibles sont:\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Ces opérations peuvent être aussi directement être utilisées sur un df (ou sur certaines lignes/colonnes) comme par exemple `df.mean(axis=1)` pour calculer la moyenne de chaque ligne."
```suggestion
    "Ces opérations peuvent être aussi directement utilisées sur un df (ou sur certaines lignes/colonnes) comme par exemple `df.mean(axis=1)` pour calculer la moyenne de chaque ligne."
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Le format CSV existe depuis très longtemps et sa simplicité le permet d'être très souvent disponible comme format d'exportation de données dans plusieurs logiciels. Cependant, il est loin d'être
```suggestion
    "Le format CSV existe depuis très longtemps et sa simplicité lui permet d'être très souvent disponible comme format d'exportation de données dans plusieurs logiciels. Cependant, il est loin d'être très efficace et présente beaucoup de désavantages: lecture lente d'une colonne spécifique, pas de compression par défaut, faible support pour les caractères spéciaux et l'hétérogénéité des types de données. Pour une faible quantité de données, le format CSV reste très pratique, toutefois, si l'on manipule une grande quantité de données, il est recommandé d'utiliser le format [Parquet](https://en.wikipedia.org/wiki/Apache_Parquet). C'est un format moderne et très performant qui permet de stocker des données en prenant 2 à 10 fois moins de place et avec une vitesse de lecture 10 à 100 fois plus rapide. Parquet est intégré à Pandas et peut être utilisé avec les méthodes `pd.read_parquet()` et `df.to_parquet()`."
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "À partir de liste des numéros CAS uniques, les ratios massique pour chaque molécule ont été extraites dans un autre fichier csv. Cette extraction a été possible grace aux librairies python open
```suggestion
    "À partir d'une liste des numéros CAS uniques, les ratios massique pour chaque molécule ont été extraites dans un autre fichier csv. Cette extraction a été possible grâce aux librairies python open source: \n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "- Rejoindre les deux tableaux grace au numéro CAS."
```suggestion
    "- Rejoindre les deux tableaux grâce au numéro CAS."
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Généralement, lors de la manipulation de données tabulaire, il est souvent très possible d'être en présence de lignes dupliquées. On peut vérifier ça avec la méthode `.duplicated()` qui renvoie
```suggestion
    "Généralement, lors de la manipulation de données tabulaires, il est souvent très possible d'être en présence de lignes dupliquées. On peut vérifier ça avec la méthode `.duplicated()` qui renvoie un masque binaire avec `True` pour les lignes dupliquées en trop. Dans notre cas, cette méthode est évaluée uniquement sur les lignes de la colonne \"cas\". "
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Pour calculer la quantité molaire par gramme de substance, on doit multiplier les fractions massiques par l'inverse de la masse molaire de l'élément. Les masses molaires des éléments atomiques s
```suggestion
    "Pour calculer la quantité molaire par gramme de substance, on doit multiplier les fractions massiques de chaque élément par l'inverse de leur masse molaire respective, puis additionner les résultats. Les masses molaires des éléments atomiques se trouvent dans un autre fichier csv: `table_periodique.csv`."
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "L'opération que l'on veut faire est principalement une multiplication matricitielle entre 2 matrices: A x B, sauf que ici on a des `DataFrame` plutot que des matrices. La particularité qui expli
```suggestion
    "L'opération que l'on veut faire est principalement une multiplication matricielle entre 2 matrices: A x B, sauf qu'ici on a des `DataFrame` plutôt que des matrices. La particularité qui explique que l'utilisation d'un `DataFrame` est plus judicieuse, est que la multiplication matricielle est effectuée uniquement entre les mêmes éléments atomiques. Pandas s'occupe de l'alignement entre les colonnes du df A et les index du df B. Cependant, avant d'effectuer la multiplication, il faut s'assurer que les deux df sont de dimensions compatibles c'est à dire que le nombre de colonnes de A est égal au nombre de lignes de B.\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "# Créer une nouvelle serie appelée qte avec le résultat de la multiplication\n",
Appelée qte ?

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "df_chempy.rename(columns={\"mass\": \"mol/g\"}, inplace=True)"
Pour être plus rigoureux, je referais l'inverse de la quantité molaire par masse (mol/g) pour avoir des masses molaires (g/mol) à la place. C'est quelque chose de beaucoup plus couramment utilisé en chimie et c'est une caractéristique importante. Donc mettre en contexte qu'on passe de mol/g à g/mol pour retrouver la masse molaire de la molécule étudiée.

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "# Explication: Cela veut dire que toutes les colonnes de df_chempy, sauf celle qui a servit de clé pour le merge, soit\n",
```suggestion
    "# Explication: Cela veut dire que toutes les colonnes de df_chempy, sauf celle qui a servi de clé pour le merge, soit\n",
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Pour retirer des lignes ou colonnes non voulues ou vides, Pandas met à disposition les méthodes `df.drop()` et `df.dropna()`."
```suggestion
    "Pour retirer des lignes ou colonnes non désirées ou vides, Pandas met à disposition les méthodes `df.drop()` et `df.dropna()`."
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "- Dans la plupart des cas, les données utilisées dépassent rarement le million de lignes. Cependant, dans le cas contraire, il faut commencer à prendre en compte la taille des données et ce que
```suggestion
    "- Dans la plupart des cas, les données utilisées dépassent rarement le million de lignes. Cependant, dans le cas contraire, il faut commencer à prendre en compte la taille des données et ce que ça implique en terme d'utilisation de la mémoire. Très souvent cela consiste à limiter le nombre de copies que l'on fait et à adopter une structure de tableau plus compacte afin de diminuer sa taille. C'est un sujet un peu plus avancé mais tout de même interessant à savoir si on a l'intention de travailler avec du Big Data et construire des algorithmes qui roulent en temps réel par exemple."
```

2022-07-13 14:48 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "Un `DataFrame` est une structure de données tabulaires qui permet de stocker et manipuler des données de façon intuitive. Les données tabulaires sont organisées sous plusieurs colonnes avec plus
Je dirais que l'acronyme df sera utilisée pour décrire un Dataframe, que ce soit dans l'explication ou le code lui-même, afin d'alléger la lecture.

2022-07-13 14:49 UTC, bibeauv commented on theme4/theme4.ipynb
> +    "| `sum`, `prod`    | Somme, Produit           |\n"
Sur VS Code ça marche aussi

2022-07-18 16:32 UTC, merged