WIP - Theme5
gch-poly/gch-python pull request #5
Opened 2022-07-06 17:30 UTC by samayala22

- [X] Exemple 1
- [X] Exemple 2
- [X] Exemple 3
- [X] Exemple 4
- [X] Lexique

2022-07-11 01:10 UTC, blaisb requested changes

2022-07-11 01:10 UTC, blaisb commented on theme5/theme5.ipynb
> +    "En biochimie, la cinématique de Michaelis-Menten est un modèle de cinématique très connu qui est utilisée pour décrire la cinématique d'une réaction catalysée par une enzyme agissant sur un subs
J'ai l'impression que cette explication n,est plus adéquate?

2022-07-27 04:15 UTC, blaisb approved these changes
J'ai genre quasiment rien à dire, mais je trouve les résultats de l'exemple 3 un peu weird. Pas sûr s'il vaut vraiment la peine. On pourra parler du 3 à mon retour, mais les 1,2,4 c'est super bon. Beau boulot!

2022-07-27 04:15 UTC, blaisb commented on theme5/theme5.ipynb
> +    "- Résoudre des ODE linéaires et non-linéaires\n",
```suggestion
    "- Résoudre des équations différentielles ordinaires (EDO, ou ODE en anglais) linéaires et non-linéaires\n",
```

2022-07-27 04:15 UTC, blaisb commented on theme5/theme5.ipynb
> +    "- Résoudre un système d'ODE\n",
Je pense que ça serait mieux d'utiliser la nomenclature EDO plutôt qu'ODE comme les trucs sont en français.

2022-07-28 18:49 UTC, samayala22 commented on theme5/theme5.ipynb
> +    "- Résoudre un système d'ODE\n",
À en parler puisque vu que la documentation en ligne est généralement en anglais.

2022-07-29 20:08 UTC, bibeauv requested changes
J'aime vraiment ce thème, simple, rapide et utile :)
Certains petits commentaires pour améliorer un peu, rien de majeur !
GG

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "- Résoudre un système d'ODE\n",
Je suis d'accord !
À la limite, juste dire :
Résoudre un système d'équations différentielles ordinaires (EDO) ou ODE en anglais.

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "- **Scipy**: est une librairie Python open-source utilisée pour le calcul scientifique. SciPy contient des modules pour l'optimisation, l'algèbre linéaire, l'intégration, l'interpolation, les fo
```suggestion
    "- **Scipy**: est une librairie Python open-source utilisée pour le calcul scientifique. SciPy contient des modules pour l'optimisation, l'algèbre linéaire, l'intégration, l'interpolation, les fonctions spéciales, les transformées de Fourier (FFT), le traitement du signal et de l'image, les solveurs ODE et d'autres tâches courantes en sciences et en ingénierie.\n",
```

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "# Le 1er argument doit toujours être t\n",
```suggestion
    "# Le 1er argument doit toujours être la variable indépendante (par exemple, le temps t)\n",
```

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "Il faut noter que `sim1.y` est une matrice qui contient la solution d'une variable sur chaque ligne. Puisque dans cet exemple on résout une seule équation, alors la matrice est de dimension 1xN
Peut-être spécifier que N c'est la longueur du vecteur temps.

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "Notez ici que le pas de temps est déterminé automatiquement mais peut être spécifié en passant à `solve_ivp` un vecteur qui contient les valeurs de temps ou l'on veut évaluer l'ODE avec l'argume
Ici je ferais la distinction entre "pas de temps" et "évaluation de la fonction sur des points dans le temps".
Pour moi, un pas de temps réfère à la méthode numérique et il est intégré automatiquement (ex. RK45).

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "La résolution numérique d'ODEs à conditions initiales avec Scipy est très simple puisque qu'elle necessite qu'une seule fonction: [`solve_ivp`](https://docs.scipy.org/doc/scipy/reference/generat
Utiliser le "s" à chaque fois que le pluriel est présent. Il n'est pas partout je crois :)

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "# Tracer les courbes de concentration\n",
Suggestion :
Peut-être revenir sur le fait que "sim" est une matrice, mais cette fois-ci de dimension 4XN.

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "Dans un système masse-ressort amorti, une masse est connectée à un ressort et à un amortisseur qui sont eux fixés à une paroi fixe. La masse est initialement étirée de sa position naturelle et e
```suggestion
    "Dans un système masse-ressort amorti, une masse est connectée à un ressort et à un amortisseur qui sont eux fixés à une paroi fixe. La masse est initialement étirée de sa position naturelle et est ensuite relâchée. En considérant que le frottement est négligeable et en appliquant la deuxième loi de Newton sur le système, on en déduit l’équation différentielle du mouvement de la masse:\n",
```

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "L'objectif de cet exemple est d'explorer comment modifier la précision de résolution d'un système d'ODE. Sans rentrer dans des détails techniques, les méthodes numériques utilisées dans les solv
```suggestion
    "L'objectif de cet exemple est d'explorer comment modifier la précision de résolution d'un système d'ODE. Sans rentrer dans des détails techniques, les méthodes numériques utilisées dans les solveurs permettent de trouver une une estimation d'erreur, qui est minimisée pour être inférieure au maximum de l'un des deux types de tolérances:\n",
```

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "- `rtol`: tolérance de l'erreur relative. Cette dernière est calculée relativement à la grandeur de la valeur même. Simplement dit, cette tolérance permet de controler le nombre de chiffres sign
```suggestion
    "- `rtol`: tolérance de l'erreur relative. Cette dernière est calculée relativement à la grandeur de la valeur même. Simplement dit, cette tolérance permet de contrôler le nombre de chiffres significatifs des valeurs qui *ne sont pas proches* de 0. \n",
```

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "Pour plus d'informations voir cette [explication](https://www.mathworks.com/help/simbio/ug/selecting-absolute-tolerance-and-relative-tolerance-for-simulation.html).\n",
```suggestion
    "Pour plus d'informations, voir cette [explication](https://www.mathworks.com/help/simbio/ug/selecting-absolute-tolerance-and-relative-tolerance-for-simulation.html).\n",
```

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "Dans Scipy, ces tolérances sont par défaut: 1e-3 pour `rtol` et 1e-6 pour `atol`. Elles peuvent être modifiées en fournissant un nouveau nombre décimal ou un vecteur de nombres décimaux pour con
```suggestion
    "Dans Scipy, ces tolérances sont par défaut: 1e-3 pour `rtol` et 1e-6 pour `atol`. Elles peuvent être modifiées en fournissant un nouveau nombre décimal ou un vecteur de nombres décimaux pour contrôler la précision dans chaque équation. "
```

2022-07-29 20:08 UTC, bibeauv commented on theme5/theme5.ipynb
> +    "En prenant l'intervalle de temps `[2,4]`, on peut voir que la courbe obtenue avec un `rtol` élevé est significativement moins précise. En revanche, la courbe avec un `atol` élevé est confondue a
```suggestion
    "En prenant l'intervalle de temps `[2,4]`, on peut voir que la courbe obtenue avec un `rtol` élevé est significativement moins précise. En revanche, la courbe avec un `atol` élevé est confondue avec la courbe `default` ce qui est attendu puisque que les valeurs de la courbe ne sont pas proches de zéro, ce qui signifie que `rtol` contrôle davantage l'erreur."
```

2022-08-01 21:47 UTC, merged